name: Create Archive
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Substitute Environment Variables
      run: |
        awk -v var=${{ vars.EXTENSION_KEY }} -i inplace '{sub(/EXTENSION_KEY/,var); print}' src/manifest.json
        awk -v var=${{ vars.OAUTH_CLIENT_ID }} -i inplace '{sub(/OAUTH_CLIENT_ID/,var); print}' src/manifest.json
        awk -v var=${{ vars.FIREBASE_API_KEY }} -i inplace '{sub(/FIREBASE_API_KEY/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_AUTH_DOMAIN }} -i inplace '{sub(/FIREBASE_AUTH_DOMAIN/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_PROJECT_ID }} -i inplace '{sub(/FIREBASE_PROJECT_ID/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_STORAGE_BUCKET }} -i inplace '{sub(/FIREBASE_STORAGE_BUCKET/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_MESSAGING_SENDER_ID }} -i inplace '{sub(/FIREBASE_MESSAGING_SENDER_ID/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_APP_ID }} -i inplace '{sub(/FIREBASE_APP_ID/,var); print}' src/config.js
        awk -v var=${{ vars.FIREBASE_MEASUREMENT_ID }} -i inplace '{sub(/FIREBASE_MEASUREMENT_ID/,var); print}' src/config.js
        awk -v var=${{ vars.FIRESTORE_COLLECTION }} -i inplace '{sub(/FIRESTORE_COLLECTION/,var); print}' src/config.js
        awk -v var=${{ vars.SEGMENT_WRITE_KEY }} -i inplace '{sub(/SEGMENT_WRITE_KEY/,var); print}' src/config.js
    - name: Archive Debug
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'test.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Remove Debug
      run: awk -i inplace '!/DEBUG/' src/index.js
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'src/'
        filename: '../release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig test.zip /src/debug.js'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip, test.zip"
        token: ${{ secrets.GITHUB_TOKEN }}    

