name: Create Archive
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Substitute Environment Variables
      echo: $EXTENSION_KEY
      run: awk -i inplace '{sub(/EXTENSION_KEY/,ENVIRON["EXTENSION_KEY"]); print}' src/index.js
    - name: Archive Debug
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'test.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Remove Debug
      run: awk -i inplace '!/DEBUG/' src/index.js
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'src/'
        filename: '../release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig test.zip /src/debug.js'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip, test.zip"
        token: ${{ secrets.GITHUB_TOKEN }}    

